[package]
name = "nydus-api"
version = "0.1.2"
description = "APIs for Nydus Image Service"
authors = ["The Nydus Developers"]
license = "Apache-2.0 OR BSD-3-Clause"
homepage = "https://nydus.dev/"
repository = "https://github.com/dragonflyoss/image-service"
edition = "2018"

[dependencies]
dbs-uhttp = { version = "0.3.0" }
http = "0.2.1"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4.8"
mio = { version = "0.8", features = ["os-poll", "os-ext"]}
serde = { version = "1.0.110", features = ["rc"] }
serde_derive = "1.0.110"
serde_json = "1.0.53"
url = "2.1.1"
vmm-sys-util = "0.10"

nydus-error = { version = "0.2", path = "../error" }
nydus-utils = { version = "0.3", path = "../utils" }
